config/routes.rb
AppThree::Application.routes.draw do
  resources :questions

  resources :flyers

    root :to => 'flyers#index'

end

app/models/flyer.rb
class Flyer < ActiveRecord::Base
 has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions
  attr_accessible :title,:description, :questions_attributes
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :subject, :flyer_id
  belongs_to :flyer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flyers_controller.rb
class FlyersController < ApplicationController
  # GET /flyers
  # GET /flyers.json
  def index
    @flyers = Flyer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flyers }
    end
  end

  # GET /flyers/1
  # GET /flyers/1.json
  def show
    @flyer = Flyer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flyer }
    end
  end

  # GET /flyers/new
  # GET /flyers/new.json
  def new
    @flyer = Flyer.new
  end

  # GET /flyers/1/edit
  def edit
    @flyer = Flyer.find(params[:id])
  end

  # POST /flyers
  # POST /flyers.json
  def create
    @flyer = Flyer.new(params[:flyer])
    #respond_to do |format|
    respond_to do |format| 
      if @flyer.save
        kit = IMGKit.new(render_to_string(:partial => 'form', :layout => false,:locals => {:flyer => @flyer}))
        #render :text=>params and return false
        #kit.stylesheets << "#{Rails.root.to_s}/app/assets/stylesheets/ImgKit.css" #its apply the give css to the converted image 
        t = kit.to_img(:png) # convert image to specific format
        file = kit.to_file(Rails.root + "public/assets/" + "screenshot.png")#storing path of converted file

        format.html { redirect_to @flyer, notice: 'Flyer was successfully created.' }
        format.json { render json: @flyer, status: :created, location: @flyer }
      else
        format.html { render action: "new" }
        format.json { render json: @flyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flyers/1
  # PUT /flyers/1.json
  def update
    @flyer = Flyer.find(params[:id])

    respond_to do |format|
      if @flyer.update_attributes(params[:flyer])
        format.html { redirect_to @flyer, notice: 'Flyer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flyers/1
  # DELETE /flyers/1.json
  def destroy
    @flyer = Flyer.find(params[:id])
    @flyer.destroy

    respond_to do |format|
      format.html { redirect_to flyers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flyers_helper.rb
module FlyersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/flyers/_form.html.erb
<%= nested_form_for(@flyer) do |f| %>
  <% if @flyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flyer.errors.count, "error") %> prohibited this flyer from being saved:</h2>

      <ul>
      <% @flyer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
 
  <%= f.fields_for :questions do |q| %>
    <%= q.label :subject, :class => 'control-label' %>
    <%= q.text_field :subject, :class => 'text_field'%><br>
    <%= q.label :content, :class => 'control-label' %>
    <%= q.text_area :content, :class => 'text_field',:rows=>3 %>
    <%= q.link_to_remove "Remove this question" %>
  <% end %>
  <p><%= f.link_to_add "Add a question", :questions %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


   

app/views/flyers/edit.html.erb
<h1>Editing flyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @flyer %> |
<%= link_to 'Back', flyers_path %>

app/views/flyers/index.html.erb
<h1>Listing flyers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flyers.each do |flyer| %>
  <tr>
    <td><%= flyer.title %></td>
    <td><%= flyer.description %></td>
    <td><%= link_to 'Show', flyer %></td>
    <td><%= link_to 'Edit', edit_flyer_path(flyer) %></td>
    <td><%= link_to 'Destroy', flyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to (image_tag asset_path("/assets/screenshot.png")), edit_flyer_path(flyer) %></td>
  </tr>
<% end %>
</table>

<br/>

<%= link_to 'New Flyer', new_flyer_path %>

app/views/flyers/new.html.erb
<h1>New flyer</h1>

<%= render 'form' %>

<%= link_to 'Back', flyers_path %>

app/views/flyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @flyer.title %>
</p>

<p>
  <b>Description:</b>
  <%= @flyer.description %>
</p>


<%= link_to 'Edit', edit_flyer_path(@flyer) %> |
<%= link_to 'Back', flyers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppThree</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.subject %></td>
    <td><%= question.content %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @question.subject %>
</p>

<p>
  <b>Content:</b>
  <%= @question.content %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>